[sdl]
fullscreen = false
fulldouble = false
fullresolution = desktop
windowresolution = 1024x768
output = opengl

[cpu]
cycles = auto

[autoexec]
# Os comandos abaixo serão executados automaticamente pelo DOSBox
@ECHO OFF
MOUNT C "C:\Users\User\Downloads\Telegram Desktop\launcher_dos\games\footman2"
C:
cls
LOADER.COM
EXIT