[sdl]
fullscreen = false
fulldouble = false
fullresolution = desktop
windowresolution = 1024x768
output = opengl

[cpu]
cycles = auto

[autoexec]
@ECHO OFF
MOUNT C "C:\Users\User\Downloads\Telegram Desktop\launcher_DosBox V. 0.74-3\games\fallout_1"
C:
cls
FALLOUT.EXE
EXIT